"""Fix foreign key relationships

Revision ID: b409d1872ae6
Revises: aeac6fa59a53
Create Date: 2025-02-17 13:27:18.633011

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b409d1872ae6'
down_revision: Union[str, None] = 'aeac6fa59a53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
